In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5110],
        [0.5694],
        [0.5551],
        [0.5818],
        [0.5836],
        [0.5287],
        [0.5895],
        [0.5520],
        [0.5395],
        [0.5267]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0361, -0.1681,  0.3725,  0.0108, -0.0474]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.1168], requires_grad=True)

In [ ]:
# To visualize the network
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Multi layer netowrk

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4265],
        [0.4263],
        [0.4166],
        [0.4293],
        [0.4300],
        [0.4423],
        [0.4509],
        [0.4335],
        [0.4382],
        [0.4321]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.0351, -0.1770, -0.0377,  0.4159,  0.1553],
        [-0.2165,  0.4039,  0.2463, -0.0771, -0.2328],
        [ 0.3174,  0.2046,  0.3022, -0.2440,  0.0148]], requires_grad=True)

In [ ]:
# show model weights
model.linear2.weight

Parameter containing:
tensor([[ 0.1047, -0.0292, -0.4390]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.0860,  0.2701,  0.3205], requires_grad=True)

In [ ]:
# show model weights
model.linear2.bias

Parameter containing:
tensor([0.0256], requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Using Containers

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


  def forward(self, features):

   out = self.network(features)
   return out

In [ ]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3843],
        [0.3772],
        [0.3642],
        [0.3822],
        [0.3743],
        [0.3822],
        [0.3822],
        [0.3822],
        [0.3769],
        [0.3822]], grad_fn=<SigmoidBackward0>)